language: python
sudo: required
python:
  - "2.7"
  - "3.6"
env:
  global:
    - TZ=Europe/Kiev
install:
  - pip install -r requirements.txt
script:
  - python -m nose --with-coverage
after_success:
  - coveralls
